title: /dev/null
author: npc_strider
email: npc-strider@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  It just works!
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 10
paginate_path: "/code/page:num/"
baseurl: "/code" # the subpath of your site, e.g. /blog
production_url: "https://npc-strider.github.io/code" # the base hostname & protocol for your site, e.g. http://example.com

# tag_permalink_style: pretty
# tag_page_layout: tag_page
# tag_page_dir: tag

dash:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://www.youtube.com/c/npcstrider
      icon: youtube
      color: red
    - url: https://steamcommunity.com/id/morley376
      icon: steam
      color: red
    - url: https://github.com/npc-strider
      icon: github-square
      color: blue

  show_author: true

  animation_speed: 50

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll-sitemap
 - liquid-md5
#  - jekyll/tagging

# Replaces the default avatar provider (gravatar)
avatar_source: github
github_username: npc-strider
